import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import type { App } from 'vue'

// Solid icons
import {
  faArrowLeft,
  faArrowRight,
  faBars,
  faBolt,
  faBomb,
  faBook,
  faCheck,
  faChevronDown,
  faChevronUp,
  faCircleExclamation,
  faCompass,
  faCircleInfo,
  faCopy,
  faDice,
  faFaceLaughSquint,
  faFire,
  faFloppyDisk,
  faGamepad,
  faGear,
  faGhost,
  faHandPointRight,
  faHouse,
  faImages,
  faLock,
  faLockOpen,
  faMagnifyingGlass,
  faMinus,
  faPause,
  faPepperHot,
  faPlay,
  faPlus,
  faPoo,
  faRotate,
  faRotateRight,
  faShuffle,
  faSkull,
  faSkullCrossbones,
  faSliders,
  faSpinner,
  faStar,
  faStopwatch,
  faToiletPaper,
  faTrash,
  faTriangleExclamation,
  faTrophy,
  faTv,
  faWandMagicSparkles,
  faUpRightFromSquare,
  faUserSecret,
  faUsers,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

// Register icons
library.add(
  // UI
  faArrowLeft,
  faArrowRight,
  faBars,
  faBolt,
  faCheck,
  faChevronDown,
  faChevronUp,
  faCopy,
  faPlus,
  faSpinner,
  faTv,
  faXmark,
  // Navigation
  faBook,
  faCircleInfo,
  faCompass,
  faGear,
  faHouse,
  faUpRightFromSquare,
  // Game
  faDice,
  faGamepad,
  faImages,
  faLock,
  faLockOpen,
  faMagnifyingGlass,
  faMinus,
  faPause,
  faPlay,
  faRotate,
  faShuffle,
  faStar,
  faTrophy,
  faWandMagicSparkles,
  faUserSecret,
  faUsers,
  // Shit-talking icons
  faBomb,
  faFaceLaughSquint,
  faFire,
  faGhost,
  faHandPointRight,
  faPepperHot,
  faPoo,
  faSkull,
  faToiletPaper,
  // Pressure mode
  faCircleExclamation,
  faRotateRight,
  faSkullCrossbones,
  faStopwatch,
  // Settings
  faFloppyDisk,
  faSliders,
  faTrash,
  // Warnings
  faTriangleExclamation
)

export function setupFontAwesome(app: App): void {
  app.component('FontAwesomeIcon', FontAwesomeIcon)
}
